plugins {
    id 'java'
}

group = 'me.naulbimix'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly fileTree(dir: 'libs', include: ['*.jar'])
    compileOnly fileTree(dir: 'C:/Program Files/JetBrains/IntelliJ IDEA 2024.3.5/lib', include: ['*/**.jar', '*.jar'])
}